import type { Property } from '@/modules/shared/domain/models/property.model';
import type { PropertyResponseDto } from '../../dtos/property-response.dto';

export const mapPropertyToModel = (propertyDto: PropertyResponseDto): Property => ({
  name: propertyDto.name,
  address: propertyDto.address,
  price: propertyDto.price,
  buildYear: propertyDto.year,
  description: propertyDto.description,
  bathrooms: propertyDto.bathrooms,
  bedrooms: propertyDto.bedrooms,
  area: propertyDto.areaSqm,
  highlightedFeatures: propertyDto.highlightedFeatures,
  amenities: propertyDto.amenities,
  featured: propertyDto.featured,
  images: propertyDto.images,
  coverImage: propertyDto.coverImage,
  views360Url: propertyDto.views360Url,
  city: propertyDto.city,
  state: propertyDto.state,
  country: propertyDto.country,
  location: propertyDto.location,
  ownerId: propertyDto.idOwner,
  status: propertyDto.status,
  type: propertyDto.type,
  id: propertyDto.id,
  internalCode: propertyDto.codeInternal,
  createdAt: propertyDto.createdAt,
  updatedAt: propertyDto.updatedAt,
});
